Bt 1047 BUIL 3532
MV-Clouds/Buildertek pull request #95
Opened 2023-09-21 11:02 UTC by Karan3036

Done

2023-09-25 06:58 UTC, Nishitsuthar requested changes

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/aura/NewContractItem/NewContractItemHelper.js
please follow the best practices whenever calling another apex method inside an apex callout in aura
please refer this links to follow best practices - [Link1](https://salesforce.stackexchange.com/questions/191389/simple-example-on-how-to-use-promises-to-call-auraenabled-apex-methods) [Link2](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_promises.htm)

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/aura/NewContractItem/NewContractItemHelper.js
@Karan3036

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +                    changeOrderIdSet.add(changeOrder.Id);
what is the usage of  `changeOrderIdSet` ?? @Karan3036

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +            if(changeOrdersList !=null){
```suggestion
            if( changeOrdersList.size() >  0){
```
instead of checking the null, you should check for the size of a List @Karan3036

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +                if(contractId != null ){
unnecessary condition check @Karan3036

2023-09-25 06:58 UTC, Nishitsuthar commented on force-app/main/default/aura/BT_NewChangeOrderLine/BT_NewChangeOrderLine.cmp
> +            <div class="slds-modal__container confirmationPopup1 rkclass">
please improve your naming convention @Karan3036 
By reading class name I can not able to understand what exactly this class does

2023-09-25 11:40 UTC, Karan3036 commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +                    changeOrderIdSet.add(changeOrder.Id);
Removed that changeOrderIdSet form code.

2023-09-25 11:40 UTC, Karan3036 commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +            if(changeOrdersList !=null){
Changed the code as per the suggestion.

2023-09-25 11:41 UTC, Karan3036 commented on force-app/main/default/aura/BT_NewChangeOrderLine/BT_NewChangeOrderLine.cmp
> +            <div class="slds-modal__container confirmationPopup1 rkclass">
Removed that class and use confirmationPopup1 in css.

2023-09-25 11:41 UTC, Karan3036 commented on force-app/main/default/classes/ChangeOrderTriggerHandler.cls
> +                if(contractId != null ){
Removed the unnecessary condition.

2023-09-26 12:24 UTC, Nishitsuthar approved these changes

2023-09-26 12:26 UTC, merged